### ISSUE TITLE
Can't create new skills

### ISSUE THREAD

**Issue by olieolieolieoli** [backstage-technical-services/hub#132]
#### Summary

Error screen when creating new skills

#### Actual behaviour
![image](https://user-images.githubusercontent.com/83349452/116403206-36b4b180-a825-11eb-87f2-966a4815432e.png)
![Uploading image.png…]()

Error 500

#### Expected behaviour

Create new skill

#### Steps to reproduce

Creating a new skill

#### When did it happen?

13:25, 28/4/21

#### Urgency

High - need to create new skills

**Comment by bnjns** [comment]
Again, we need way more information for reproducing.

**Comment by olieolieolieoli** [comment]
Tried to create a new skill in normal way (training skills area, 'create skill' button), filled in the skill details as per the screenshot, created skill and went to an error screen (error 500).
![image](https://user-images.githubusercontent.com/83349452/116405632-c52a3280-a827-11eb-95e6-b46a86ddbc67.png)

**Comment by bnjns** [comment]
Is this only for uncategorised skills? If so, I can see what the issue is.

**Comment by olieolieolieoli** [comment]
Just checked and works if not uncategorised - can still move skills over in the meantime so can shift down to a low priority/not need fixing

**Comment by bnjns** [comment]
For anyone who picks this up, the issue is that uncategorised skills are an empty space in the request, but need to be converted to `null` before set in the skill - otherwise this violates the constraint on that column.

The offending line is https://github.com/backstage-technical-services/laravel-site/blob/master/app/Http/Controllers/Training/Skills/SkillController.php#L60, along with any similar usages (eg, updating?).

We can probably fix fairly quickly.
