### ISSUE TITLE
Issues approving awards

### ISSUE THREAD

**Issue by nbibaud** [backstage-technical-services/hub#137]
#### Summary

Pressing "approve" for submissions on the nominations page often doesn't actually approve the nomination

#### Actual behaviour

Pressing "approve" only rarely actually approved the award nomination, with no apparent predictability. When it didn't approve the nomination, I'd often get a "nomination unapproved" pop-up, and sometimes both a "nomination approved" and "nomination unapproved" popup at the same time. Often I needed to refresh the page (sometimes several times) until it would work. Sometimes I could then approve several nominations in a row before it broke again; sometimes only one.

#### Expected behaviour

Should approve the nomination and change the red x on the left to a tick

#### Steps to reproduce

Had created an award, and had it in "nominations open" status, with nominations having been submitted. Pressed the "approve nomination" button.

#### When did it happen?

25/05, around 9pm

#### Urgency

Medium - I'm done with approving nominations now but it took me about 50 mins so does need to be fixed for the next time someone does this - it was bloody annoying

**Comment by bnjns** [comment]
I think this is the same issue as #135 and #136. It looks like the JS we use for all the AJAX calls fails to process the response sometimes and then retries, so you're essentially approving an award and then immediately unapproving.

This might need a complete ground-up rewrite of this module, and so far it doesn't look like anyone has time to take a look :confused: 

I think I'm going to combine all of these together into 135, but I'd still encourage adding details to that ticket - and do join the Slack workspace if you want to chat directly rather than through GitHub!
