### ISSUE TITLE
When navigating through pages of events in profiles it redirects back to details page

### ISSUE THREAD

**Issue by jamieernest** [backstage-technical-services/hub#141]
#### Summary

When a page that is not the current page in the events page of a profile is selected it redirects back to the details page.

#### Actual behaviour

Details page is shown after clicking on ">>" or any page number, however when pressing back on the events tab the correct events page displays.

#### Expected behaviour

After clicking on the page number it should show the page selected on the events page instead of the details page

#### Steps to reproduce

Go to a profile of a member that has more than 1 page of events crewed, click on any page other than the currently displayed one, or "<<"/">>", and the details page is shown

#### When did it happen?

23/10/24 1644z

#### Urgency

Low, just a slightly annoying quirk

**Comment by bnjns** [comment]
I can see what's happening here - because we don't set the active link, the package (`js-tabify`) just defaulting to the first element.

**Comment by bnjns** [comment]
Cool, I've identified the issue. It's because we're now behind a load balancer that terminates TLS so the app is in "http mode". I'd previously ... [hacked this](https://github.com/backstage-technical-services/website/blob/a726e68030c8bd7b051150f254d650b936e1477f/app/Providers/AppServiceProvider.php#L20) so that it generates HTTPS links, but it still classifies the incoming request as HTTP.

The library we use compares the link in the menu item with the actual URL to determine if it should set the link as "active", but that fails because link is HTTPS, but request is HTTP. This is why it works locally but not staging/production.

We can instead configure a trusted proxy and the app will correctly use the forwarded headers to set the request/URL scheme to HTTPS.

**Comment by bnjns** [comment]
Deployed to production. Confirmed as fixed.
